"""deep_analysis_reports

Revision ID: d8381ce6d30d
Revises: e9f0a1b2c3d4
Create Date: 2026-07-29 12:17:54.575049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8381ce6d30d'
down_revision: Union[str, Sequence[str], None] = 'e9f0a1b2c3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deep_analysis_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('market', sa.String(length=4), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('normalized_ticker', sa.String(length=32), nullable=False),
    sa.Column('analysis_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.SmallInteger(), nullable=False),
    sa.Column('attempt_count', sa.SmallInteger(), nullable=False),
    sa.Column('max_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.Column('claim_token', sa.UUID(), nullable=True),
    sa.Column('lease_version', sa.Integer(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('conclusion_status', sa.String(length=24), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('credit_state', sa.String(length=16), nullable=False),
    sa.Column('reserved_credits', sa.Integer(), nullable=False),
    sa.Column('settled_credits', sa.Integer(), nullable=False),
    sa.CheckConstraint("(status = 'completed') = (result IS NOT NULL)", name='chk_deep_analysis_completed_result'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deep_analysis_owner_history', 'deep_analysis_reports', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_deep_analysis_reports_user_id'), 'deep_analysis_reports', ['user_id'], unique=False)
    op.create_index('ix_deep_analysis_stale_running', 'deep_analysis_reports', ['heartbeat_at'], unique=False, postgresql_where="status = 'running'")
    op.create_index('ix_deep_analysis_worker_claim', 'deep_analysis_reports', ['next_retry_at', 'created_at'], unique=False, postgresql_where="status IN ('pending','retry_wait')")
    op.create_index('uq_deep_analysis_active_request', 'deep_analysis_reports', ['user_id', 'market', 'normalized_ticker', 'analysis_version'], unique=True, postgresql_where="status IN ('pending','running','retry_wait') AND deleted_at IS NULL")
    op.create_index('uq_deep_analysis_idempotency', 'deep_analysis_reports', ['user_id', 'idempotency_key'], unique=True, postgresql_where='idempotency_key IS NOT NULL')
    # NOTE: autogenerate 误判删除上一步刚建的 uq_credit_tx_deep_analysis 索引，
    # 因为该 partial unique index 不在 SQLAlchemy metadata 中。它属于
    # e9f0a1b2c3d4_deep_analysis_credits，此处不触碰。
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: uq_credit_tx_deep_analysis 的误删 recreate 同样省略，归 e9f0a1b2c3d4 管理。
    op.drop_index('uq_deep_analysis_idempotency', table_name='deep_analysis_reports', postgresql_where='idempotency_key IS NOT NULL')
    op.drop_index('uq_deep_analysis_active_request', table_name='deep_analysis_reports', postgresql_where="status IN ('pending','running','retry_wait') AND deleted_at IS NULL")
    op.drop_index('ix_deep_analysis_worker_claim', table_name='deep_analysis_reports', postgresql_where="status IN ('pending','retry_wait')")
    op.drop_index('ix_deep_analysis_stale_running', table_name='deep_analysis_reports', postgresql_where="status = 'running'")
    op.drop_index(op.f('ix_deep_analysis_reports_user_id'), table_name='deep_analysis_reports')
    op.drop_index('ix_deep_analysis_owner_history', table_name='deep_analysis_reports')
    op.drop_table('deep_analysis_reports')
    # ### end Alembic commands ###
