"""fund_arb

Revision ID: e30485f629c0
Revises: d8e9f0a1b2c3
Create Date: 2026-07-20 17:26:38.528975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30485f629c0'
down_revision: Union[str, Sequence[str], None] = 'd8e9f0a1b2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_arb_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('fund_code', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_pct', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('nav', sa.Float(), nullable=True),
    sa.Column('est_nav_close', sa.Float(), nullable=True),
    sa.Column('premium', sa.Float(), nullable=True),
    sa.Column('valuation_error', sa.Float(), nullable=True),
    sa.Column('purchase_status', sa.String(length=16), nullable=True),
    sa.Column('redemption_status', sa.String(length=16), nullable=True),
    sa.Column('purchase_limit', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'fund_code', name='uq_fund_arb_daily_date_code')
    )
    op.create_index(op.f('ix_fund_arb_daily_date'), 'fund_arb_daily', ['date'], unique=False)
    op.create_index(op.f('ix_fund_arb_daily_fund_code'), 'fund_arb_daily', ['fund_code'], unique=False)
    op.create_table('fund_arb_factors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_code', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('position_beta', sa.Float(), nullable=False),
    sa.Column('r_squared', sa.Float(), nullable=False),
    sa.Column('sample_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_code', 'date', name='uq_fund_arb_factor_code_date')
    )
    op.create_index(op.f('ix_fund_arb_factors_fund_code'), 'fund_arb_factors', ['fund_code'], unique=False)
    op.create_table('fund_arb_funds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_code', sa.String(length=16), nullable=False),
    sa.Column('fund_name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('sina_symbol', sa.String(length=24), nullable=False),
    sa.Column('tracking_symbol', sa.String(length=32), nullable=False),
    sa.Column('tracking_type', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('rate_type', sa.String(length=8), nullable=False),
    sa.Column('valuation_method', sa.String(length=16), nullable=False),
    sa.Column('nav_field', sa.String(length=8), nullable=False),
    sa.Column('pos_ratio_default', sa.Float(), nullable=False),
    sa.Column('approx', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_code')
    )
    op.create_index(op.f('ix_fund_arb_funds_category'), 'fund_arb_funds', ['category'], unique=False)
    op.create_table('fund_arb_tracking_daily',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'symbol', name='uq_fund_arb_tracking_date_symbol')
    )
    op.create_index(op.f('ix_fund_arb_tracking_daily_date'), 'fund_arb_tracking_daily', ['date'], unique=False)
    op.create_index(op.f('ix_fund_arb_tracking_daily_symbol'), 'fund_arb_tracking_daily', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fund_arb_tracking_daily_symbol'), table_name='fund_arb_tracking_daily')
    op.drop_index(op.f('ix_fund_arb_tracking_daily_date'), table_name='fund_arb_tracking_daily')
    op.drop_table('fund_arb_tracking_daily')
    op.drop_index(op.f('ix_fund_arb_funds_category'), table_name='fund_arb_funds')
    op.drop_table('fund_arb_funds')
    op.drop_index(op.f('ix_fund_arb_factors_fund_code'), table_name='fund_arb_factors')
    op.drop_table('fund_arb_factors')
    op.drop_index(op.f('ix_fund_arb_daily_fund_code'), table_name='fund_arb_daily')
    op.drop_index(op.f('ix_fund_arb_daily_date'), table_name='fund_arb_daily')
    op.drop_table('fund_arb_daily')
    # ### end Alembic commands ###
